<?php

return [
    'Exception_error'                 => '0',
    'registered_before'               => '10',
    'code_send_before'                => '20',
    'code_sms_error'                  => '30',
    'code_sms_expire'                 => '40',
    'password_username_error'         => '50',
    'register_phone_error'            => '60',
    'phone_number_error'              => '65',
    'cant_creat_ride'                 => '70',
    'same_order_found_day'            => '71',
    'order_so_not_completed_ex_error' => '72',

    'code_provided_error'      => '80',
    'code_phone_error'         => '90',
    'reset_passError'          => '110',
    'remember_token_error'     => '120',
    'data_not_update'          => '130',
    'data_track_error'         => '131',
    'data_not_found'           => '140',
    'no_enough_balance'        => '141',
    'you_bought_before'        => '142',
    'invalid_posted_data'      => '143',
    'un_available_in_stock'    => '144',
    'un_subscribed'    => '145',
    'old_password_error'       => '150',
    'cant_create_dc_order'     => '151',
    'driver_active_before'     => '160',
    'current_status_error'     => '170',
    'no_active_drivers'        => '180',
    'driver_cant_accept_order' => '190',
    'rider_cant_cancel_order'  => '410',
    'wallet_balance'           => '420',
    'cant_accept_new_order'    => '430',
    'small_reserved_amount'    => '440',
    'payed_trip'               => '450',
    'null_acc_number'          => '450',
    'error_conflicting'        => '460',
    'cant_collect_money'       => '470',
    'cant_create_deliver_info' => '480',

];
